### ISSUE TITLE
Non-reproducible results across OSs, causing incompatibilities with the produced manual segmentation

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#110]
Because propseg results are slightly different across OSs (for more details, see https://github.com/neuropoly/spinalcordtoolbox/issues/2769), when running the pipeline on one OS, correcting a mask, and then re-running in another OS, the following bug could occur, when computing DTI metrics with dipy:
````
+ sct_dmri_compute_dti -i sub-tokyoSigna2_dwi_crop_moco.nii.gz -bvec sub-tokyoSigna2_dwi.bvec -bval sub-tokyoSigna2_dwi.bval -method standard -m sub-tokyoSigna2_dwi_crop_moco_dwi_mean_seg_dil.nii.gz

--
Spinal Cord Toolbox (git-cfh/sct-run-batch-improvements_2726-3fdbf4fb40879240260a9af429bf4dcbd3ee0375)

data.shape (33, 36, 15, 35)
Open mask file...
Computing tensor using "standard" method...
Traceback (most recent call last):
  File "/home/jcohen/code/sct/scripts/sct_dmri_compute_dti.py", line 208, in <module>
    main()
  File "/home/jcohen/code/sct/scripts/sct_dmri_compute_dti.py", line 120, in main
    if not compute_dti(fname_in, fname_bvals, fname_bvecs, prefix, method, evecs, file_mask):
  File "/home/jcohen/code/sct/scripts/sct_dmri_compute_dti.py", line 164, in compute_dti
    tenfit = tenmodel.fit(data, mask)
  File "/home/jcohen/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/dipy/reconst/dti.py", line 777, in fit
    raise ValueError("Mask is not the same shape as data.")
ValueError: Mask is not the same shape as data.
````

A workaround would be to regrid the mask to the DWI before running DTI fit.

**Comment by jcohenadad** [comment]
Actually, the problem is more fundamental than that: given that the cropping region differs across OSs, motion correction results also differ, and as a result the mean DWI image used to perform the 2nd segmentation also differ, hence the "manual" correction can only apply to one specific OS.

The only solution I see is to:
- get rid of the OS-specific variability in the results (get rid of propseg)
- re-do the manual segmentations

**Comment by jcohenadad** [comment]
After having second thoughts, a better approach would be to _not_ crop the DWI data before motion correction (moco), and instead create a Gaussian mask, out of centerline detefction, for accurate moco as per recent implementation in SCT. The advantage is that, if the image quality is crappy, the centerline detection would be much more robust than the 1st segmentation, and more importantly since the 1st segmentation is not reviewed (because it occurs _before_ the cropping), it makes the pipeline QC easier.

So, the following needs to be done:
**Implementation:**
- [ ] Replace propseg by get_centerline. Output QC (might need to open an SCT issue).
- [ ] Create a Gaussian mask from the centerline
- [ ] Run moco with the Gaussian mask
- [ ] Output QC (might need to open an issue in SCT for that). The QC could be a visual inspection of the mean DWI before/after moco.
- [ ] Segment the cord on the moco DWI (and offer possibility to manually correct)

**Running pipeline:**
- [ ] Make sure the pipeline is reproducible between OSs
- [ ] Remove the manual corrections for the DWI scans on both single and multi-subject datasets
- [ ] Run both pipelines (multi- and single subject)
- [ ] Correct segmentations for DWI
- [ ] Re-run both pipelines with the manual segmentations

**Comment by jcohenadad** [comment]
reopening because some of the items in https://github.com/spine-generic/spine-generic/issues/110#issuecomment-653887863 are not done
