### ISSUE TITLE
spine-generic virtual env

### ISSUE THREAD

**Issue by valosekj** [spine-generic/spine-generic#120]
I am now performing some experiments with latest version of `manual_correction.py`. Which venv do you use when run this script? When I use venv created for spine-generic repo it fails (on missing package for SCT):

```
(venv) valosek@Jan-MacBook-Pro:/usr/local/spine-generic$ python processing/manual_correction.py -config files.yml 
'fsleyes' (version: fsleyes/FSLeyes version 0.27.3+build0) is installed.
Traceback (most recent call last):
 File "/usr/local/sct/bin/sct_version", line 6, in <module>
  from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
'sct' is not installed. Please install it before using this program.
Some required software are not installed. Exit program.
(venv) valosek@Jan-MacBook-Pro:/usr/local/spine-generic$ sct_version 
git-master-a4f9b8612cf5f424f508ce51a305f7d6faad0c7e
```

When I run the script in venv_sct, it fails on missing coloredlogs package:

```
(venv_sct) valosek@Jan-MacBook-Pro:/usr/local/spine-generic$ python processing/manual_correction.py
Traceback (most recent call last):
 File "/usr/local/spine-generic/processing/manual_correction.py", line 16, in <module>
  import coloredlogs
ModuleNotFoundError: No module named 'coloredlogs'
```

**Comment by jcohenadad** [comment]
@valosekj regardless if you use it via venv or your default installed python, you should always install the deps with:
~~~
pip install -r requirements.txt
~~~

**Comment by valosekj** [comment]
Okay, installing spine-generic/requirements.txt into SCT venv (venv_sct) solved this issue:

```
valosek@Jan-MacBook-Pro:~$ source ${SCT_DIR}/python/etc/profile.d/conda.sh
valosek@Jan-MacBook-Pro:~$ conda activate venv_sct
(venv_sct) valosek@Jan-MacBook-Pro:~$ pip install -r /usr/local/spine-generic/requirements.txt
```

**Comment by jcohenadad** [comment]
fixed ^
