### ISSUE TITLE
Fix CLI scripts with new spinegeneric package

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#130]
Some scripts need some fixes after moving files around, e.g.:
~~~
julien-macbook:~/data/spine_generic_single_20200703/results $ sg_generate_figure 

Processing: DWI_RD.csv
Loop across subjects: 100%|██████████████████| 19/19 [00:00<00:00, 411.87iter/s]
Subjects removed: []
Traceback (most recent call last):
  File "/Users/julien/miniconda3/bin/sg_generate_figure", line 11, in <module>
    load_entry_point('spinegeneric', 'console_scripts', 'sg_generate_figure')()
  File "/Users/julien/code/spine-generic/spine-generic/spinegeneric/cli/generate_figure.py", line 556, in main
    ax = add_flag(i, flags[c], ax)
  File "/Users/julien/code/spine-generic/spine-generic/spinegeneric/cli/generate_figure.py", line 276, in add_flag
    img = _get_flag(name)
  File "/Users/julien/code/spine-generic/spine-generic/spinegeneric/cli/generate_figure.py", line 273, in _get_flag
    im = plt.imread(path)
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2128, in imread
    return matplotlib.image.imread(fname, format)
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/matplotlib/image.py", line 1433, in imread
    with open(fname, 'rb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/julien/code/spine-generic/spine-generic/spinegeneric/cli/flags/japan.png'
~~~

**Comment by valosekj** [comment]
For `sg_generate_figure.py` script, workaround could be fix of following line from:

https://github.com/spine-generic/spine-generic/blob/720e71ce432d18cdf935653a9ec0e96741801b3d/spinegeneric/cli/generate_figure.py#L272

to: 

`path = os.path.join(os.path.dirname(os.path.abspath(__file__)).rstrip('cli'), 'flags', '{}.png'.format(name))`

(removing `cli` from path)
