### ISSUE TITLE
sg_manual_correction fails when key in yml file is empty

### ISSUE THREAD

**Issue by valosekj** [spine-generic/spine-generic#151]
When run `sg_manual_correction` script with following yml config file:

```
FILES_SEG:
- sub-vuiisAchieva01_dwi_moco_dwi_mean.nii.gz
- sub-vuiisAchieva04_dwi_moco_dwi_mean.nii.gz
- sub-vuiisAchieva06_dwi_moco_dwi_mean.nii.gz
- sub-perform03_dwi_moco_dwi_mean.nii.gz
- sub-stanford01_dwi_moco_dwi_mean.nii.gz
- sub-sapienza01_dwi_moco_dwi_mean.nii.gz
- sub-mniS03_dwi_moco_dwi_mean.nii.gz
- sub-perform01_dwi_moco_dwi_mean.nii.gz
- sub-beijingVerio02_dwi_concat_moco_dwi_mean.nii.gz
- sub-vuiisAchieva04_dwi_moco_dwi_mean.nii.gz
FILES_GMSEG:
FILES_LABEL:
```

i.e., with setting only `FILES_SEG` key and letting other keys empty, the script fails:

```
Checking if required software are installed...
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
OSError: [Errno 9] Bad file descriptor
'fsleyes' (version: ) is installed.
'sct' (version: git-master-48496b28eec9900456eed66da73152d83c0902e2*) is installed.
Traceback (most recent call last):
  File "/usr/local/bin/sg_manual_correction", line 33, in <module>
    sys.exit(load_entry_point('spinegeneric', 'console_scripts', 'sg_manual_correction')())
  File "/usr/local/spine-generic/spinegeneric/cli/manual_correction.py", line 187, in main
    sg.utils.check_files_exist(dict_yml, args.path_in)
  File "/usr/local/spine-generic/spinegeneric/utils.py", line 134, in check_files_exist
    for file in files:
TypeError: 'NoneType' object is not iterable
```

**Comment by valosekj** [comment]
Looks that deleting empty keys fixes problem, so the yml file looks like:

```
FILES_SEG:
- sub-vuiisAchieva01_dwi_moco_dwi_mean.nii.gz
- sub-vuiisAchieva04_dwi_moco_dwi_mean.nii.gz
- sub-vuiisAchieva06_dwi_moco_dwi_mean.nii.gz
- sub-perform03_dwi_moco_dwi_mean.nii.gz
- sub-stanford01_dwi_moco_dwi_mean.nii.gz
- sub-sapienza01_dwi_moco_dwi_mean.nii.gz
- sub-mniS03_dwi_moco_dwi_mean.nii.gz
- sub-perform01_dwi_moco_dwi_mean.nii.gz
- sub-beijingVerio02_dwi_concat_moco_dwi_mean.nii.gz
- sub-vuiisAchieva04_dwi_moco_dwi_mean.nii.gz
```

**Comment by jcohenadad** [comment]
yup-- i figured it out and fixed the yml file you sent me eariler
