### ISSUE TITLE
sg_generate_figure fails after update to v2.3

### ISSUE THREAD

**Issue by valosekj** [spine-generic/spine-generic#176]
After update to v2.3, `sg_generate_figure` fails.

command:

`sg_generate_figure -path-results ~/spinegeneric/ds002902-download_results/results`

output:
```
Processing: DWI_RD.csv
Loop across subjects: 100%|████████████████| 236/236 [00:00<00:00, 377.98iter/s]
Subjects removed: []
Traceback (most recent call last):
  File "/usr/local/spine-generic/venv/bin/sg_generate_figure", line 11, in <module>
    load_entry_point('spinegeneric==2.3', 'console_scripts', 'sg_generate_figure')()
  File "/usr/local/spine-generic/venv/lib/python3.7/site-packages/spinegeneric/cli/generate_figure.py", line 567, in main
    ax = add_flag(i, flags[c], ax)
  File "/usr/local/spine-generic/venv/lib/python3.7/site-packages/spinegeneric/cli/generate_figure.py", line 287, in add_flag
    img = _get_flag(name)
  File "/usr/local/spine-generic/venv/lib/python3.7/site-packages/spinegeneric/cli/generate_figure.py", line 284, in _get_flag
    with importlib.resources.path(spinegeneric.flags, f'{name}.png') as path_flags:
NameError: name 'importlib' is not defined
```

(I did update in spine-generic directory by)
```
git checkout master
git fetch
git pull
pip install ./
```

**Comment by jcohenadad** [comment]
Thanks @valosekj i was rushing a bit too much-- i'll fix these issues and add more tests
