### ISSUE TITLE
Running pipeline with run_all produces errors

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#183]
(to be confirmed)

Lately i've re-run the processing using [run_all](https://github.com/sct-pipeline/csa-atrophy/blob/f17bd775917e6be4e3ee2e22ea839ecd1455973f/run_all.py), which breaks jobs across chunks of subjects (to fit the 32-core nodes on Compute Canada).

However, I ended up with 8 err.* files, with the following error:
~~~
*** Generate Quality Control (QC) html report ***
Resample images to NonexNone mm
QcImage: layout with Sagittal slice
Traceback (most recent call last):
  File "/home/jcohen/sct/scripts/sct_qc.py", line 86, in <module>
    main(arguments)
  File "/home/jcohen/sct/scripts/sct_qc.py", line 79, in main
    process=args.p)
  File "/home/jcohen/sct/spinalcordtoolbox/reports/qc.py", line 694, in generate_qc
    angle_line=angle_line
  File "/home/jcohen/sct/spinalcordtoolbox/reports/qc.py", line 560, in add_entry
    layout(qcslice)
  File "/home/jcohen/sct/spinalcordtoolbox/reports/qc.py", line 317, in wrapped_f
    self.qc_report.update_description_file(img.shape)
  File "/home/jcohen/sct/spinalcordtoolbox/reports/qc.py", line 495, in update_description_file
    self._update_html_assets(get_json_data_from_path(path_json))
  File "/home/jcohen/sct/spinalcordtoolbox/reports/qc.py", line 704, in get_json_data_from_path
    results.append(json.load(fjson))
  File "/home/jcohen/sct/python/envs/venv_sct/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/jcohen/sct/python/envs/venv_sct/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/jcohen/sct/python/envs/venv_sct/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/jcohen/sct/python/envs/venv_sct/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
~~~

**Comment by jcohenadad** [comment]
As suspected, running the whole process without run_all (ie via a single sct_run_batch command) does not yield those errors. So we need to find out the cause for this bug and fix it.
