### ISSUE TITLE
Display interactive dashboards of multi-subject results

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#222]
The purpose here would be to:
- Generate using [Heroku](https://www.heroku.com/) dashboards interactive plots of the results, so that people can check individual values
- Generate those using the csv outputs from the [latest release](https://github.com/spine-generic/data-multi-subject/releases)
  - after downloading the zipped csv files, run: `sg_generate_figure` to generate the figures and have an idea how the dashboard should look like
- Embed those dashboards inside the RTD documentation, under a new section "results"

**Comment by noemieroberge** [comment]
What is `sg_generate_figure` ? Can I find it somewhere?

**Comment by jcohenadad** [comment]
> What is `sg_generate_figure` ? Can I find it somewhere?

it is a CLI script installed with the spine-generic package, more info [in the doc](https://spine-generic.readthedocs.io/en/latest/analysis-pipeline.html#generate-figures)

**Comment by noemieroberge** [comment]
While running the script `generate_figure.py` in [spinegeneric/cli](https://github.com/spine-generic/spine-generic/tree/master/spinegeneric/cli), I get `No module named 'spinegeneric'`

**Comment by jcohenadad** [comment]
did you run it from the terminal? can you please copy/paste your terminal output?

**Comment by noemieroberge** [comment]
`noemieroberge@MacBook-Air-de-Noemie Spine-generic-dashboard % /usr/local/bin/python3 /Users/noemieroberge/Documents/GitHub/Spine-generic-dashboard/results_r20200917/generate_figure.py
Traceback (most recent call last):
  File "/Users/noemieroberge/Documents/GitHub/Spine-generic-dashboard/results_r20200917/generate_figure.py", line 35, in <module>
    import spinegeneric as sg
ModuleNotFoundError: No module named 'spinegeneric'
noemieroberge@MacBook-Air-de-Noemie Spine-generic-dashboard % `

**Comment by jcohenadad** [comment]
> /usr/local/bin/python3 /Users/noemieroberge/Documents/GitHub/Spine-generic-dashboard/results_r20200917/generate_figure.py

do not call python, use the CLI directly after installation

**Comment by noemieroberge** [comment]
Ok I used directly CLI
It seems like I have KeyError

```bash
(ProjectDashboard) noemieroberge@MacBook-Air-de-Noemie ~ % sg_generate_figure -path-results ~/spineGeneric_results/results -exclude /Users/noemieroberge/data-multi-subject/exclude.yml
Age statistics:
Traceback (most recent call last):
  File "/Users/noemieroberge/ProjectDashboard/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2891, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'median'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/noemieroberge/ProjectDashboard/bin/sg_generate_figure", line 33, in <module>
    sys.exit(load_entry_point('spinegeneric', 'console_scripts', 'sg_generate_figure')())
  File "/Users/noemieroberge/spine-generic/spinegeneric/cli/generate_figure.py", line 872, in main
    compute_age_statistics()
  File "/Users/noemieroberge/spine-generic/spinegeneric/cli/generate_figure.py", line 496, in compute_age_statistics
    age_stats['median']))
  File "/Users/noemieroberge/ProjectDashboard/lib/python3.8/site-packages/pandas/core/series.py", line 882, in __getitem__
    return self._get_value(key)
  File "/Users/noemieroberge/ProjectDashboard/lib/python3.8/site-packages/pandas/core/series.py", line 991, in _get_value
    loc = self.index.get_loc(label)
  File "/Users/noemieroberge/ProjectDashboard/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2893, in get_loc
    raise KeyError(key) from err
KeyError: 'median'

```

**Comment by jcohenadad** [comment]
@noemieroberge could you try with python 3.7?

**Comment by noemieroberge** [comment]
I tried with python 3.7 
I still have the same KeyError

```bash 
(ProjetDashboard) noemieroberge@MacBook-Air-de-Noemie ~ % sg_generate_figure -path-results ~/spineGeneric_results/results -exclude /Users/noemieroberge/data-multi-subject/exclude.yml
Age statistics:
Traceback (most recent call last):
  File "/Users/noemieroberge/ProjetDashboard/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2891, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'median'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/noemieroberge/ProjetDashboard/bin/sg_generate_figure", line 11, in <module>
    load_entry_point('spinegeneric', 'console_scripts', 'sg_generate_figure')()
  File "/Users/noemieroberge/spine-generic/spinegeneric/cli/generate_figure.py", line 872, in main
    compute_age_statistics()
  File "/Users/noemieroberge/spine-generic/spinegeneric/cli/generate_figure.py", line 496, in compute_age_statistics
    age_stats['median']))
  File "/Users/noemieroberge/ProjetDashboard/lib/python3.7/site-packages/pandas/core/series.py", line 882, in __getitem__
    return self._get_value(key)
  File "/Users/noemieroberge/ProjetDashboard/lib/python3.7/site-packages/pandas/core/series.py", line 991, in _get_value
    loc = self.index.get_loc(label)
  File "/Users/noemieroberge/ProjetDashboard/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2893, in get_loc
    raise KeyError(key) from err
KeyError: 'median'
```

**Comment by jcohenadad** [comment]
are you using results from the single or from the multi subjects repository?

**Comment by noemieroberge** [comment]
I use results from multi subjects repository. I changed the path for my results folder and it is working

**Comment by jcohenadad** [comment]
I recently came across [Bokeh](https://bokeh.org/). Maybe worth looking into?

**Comment by jcohenadad** [comment]
Example of interactive plots in RTD:
- https://github.com/readthedocs/readthedocs.org/issues/4367#issuecomment-404979311

**Comment by noemieroberge** [comment]
https://spine-generic.readthedocs.io/en/nr-dashboard/
