### ISSUE TITLE
sg_create_mosaic problems; skimage missing

### ISSUE THREAD

**Issue by alexfoias** [spine-generic/spine-generic#225]
I tried to create a mosaic from **results_multi_20200907/** on graham 

```
(sg) [alfoi@gra-login1 spineGeneric_results]$ sg_create_mosaic -ifolder ~/project/results_multi_20200907/
Traceback (most recent call last):
  File "/home/alfoi/envs/sg/bin/sg_create_mosaic", line 11, in <module>
    load_entry_point('spinegeneric', 'console_scripts', 'sg_create_mosaic')()
  File "/home/alfoi/envs/sg/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/alfoi/envs/sg/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/alfoi/envs/sg/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/alfoi/envs/sg/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/alfoi/code/spine-generic/spinegeneric/cli/create_mosaic.py", line 23, in <module>
    from skimage.exposure import equalize_adapthist, rescale_intensity
ModuleNotFoundError: No module named 'skimage'
```

**Comment by jcohenadad** [comment]
@alexfoias what if you do a `pip install scikit-image`?

**Comment by alexfoias** [comment]
I installed scikit-image and got rid of that error.

```
(sg) [alfoi@gra-login3 ~]$ sg_create_mosaic -ifolder ~/project/results_multi_20200907/
Traceback (most recent call last):
  File "/home/alfoi/envs/sg/bin/sg_create_mosaic", line 11, in <module>
    load_entry_point('spinegeneric', 'console_scripts', 'sg_create_mosaic')()
  File "/home/alfoi/envs/sg/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/alfoi/envs/sg/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/alfoi/envs/sg/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/alfoi/envs/sg/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/alfoi/code/spine-generic/spinegeneric/cli/create_mosaic.py", line 25, in <module>
    from spinalcordtoolbox.utils import __sct_dir__
ModuleNotFoundError: No module named 'spinalcordtoolbox'
```

I tried to run :  `${SCT_DIR}/python/envs/venv_sct/bin/python code/spine-generic/spinegeneric/cli/create_mosaic.py -i *T1w_RPI_r_flatten.nii.gz -ifolder ~/project/results_multi_20200907/data_processed/ -s _seg.nii.gz -p sag -col 18 -row 12 -o fig_mosaic_t1.png`

But I get the error:
```
Traceback (most recent call last):
  File "code/spine-generic/spinegeneric/cli/create_mosaic.py", line 208, in <module>
    main()
  File "code/spine-generic/spinegeneric/cli/create_mosaic.py", line 128, in main
    data = np.stack(slice_lst, axis=-1)
  File "<__array_function__ internals>", line 6, in stack
  File "/home/alfoi/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/numpy/core/shape_base.py", line 423, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
```

I think I also have a permissions problem within the folder `~/project/results_multi_20200907/`
```
(sg) [alfoi@gra-login3 ~]$ cd ~/project/results_multi_20200907/
(sg) [alfoi@gra-login3 results_multi_20200907]$ ls
data_processed	log  process_data.sh  qc  qc.zip  results  results.zip
(sg) [alfoi@gra-login3 results_multi_20200907]$ cd data_processed/
-bash: cd: data_processed/: Permission denied

```

**Comment by alexfoias** [comment]
@jcohenadad (I forgot to tag you) Any suggestions ? ^

**Comment by jcohenadad** [comment]
- `ModuleNotFoundError`: you figured it out, but you could instead [activate conda's env](https://github.com/neuropoly/spinalcordtoolbox/wiki/Misc%3A-SCT-Python)
- `ValueError`: needs a bit of debugging i'm afraid 😅 
- premission denied: i should probably move this folder under the proper project def-jcohen folder (currently it's under my project folder). I'm doing that now
