### ISSUE TITLE
`sg_params_checker`: incompatibility with new pybids?

### ISSUE THREAD

**Issue by kousu** [spine-generic/spine-generic#252]
https://github.com/spine-generic/data-multi-subject/pull/96/checks#step:13:9 (archive: [log.txt](https://github.com/spine-generic/spine-generic/files/7535685/log.txt))

```
 Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/bin/sg_params_checker", line 11, in <module>
    load_entry_point('spinegeneric==2.5.dev0', 'console_scripts', 'sg_params_checker')()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/spinegeneric/cli/params_checker.py", line 51, in main
    layout = BIDSLayout(data_path,config_filename=path_sg_layout_config,validate=False)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/bids/layout/layout.py", line 145, in __init__
    indexer(self)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/bids/layout/index.py", line 109, in __call__
    self._index_dir(self._layout._root, self._config)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/bids/layout/index.py", line 164, in _index_dir
    cfg = Config.load(config_file, session=self.session)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/bids/layout/models.py", line 156, in load
    result = session.query(Config).filter_by(name=config['name']).first()
TypeError: 'PosixPath' object is not subscriptable
Error: Process completed with exit code 1.
```

Weird bug?

**Comment by kousu** [comment]
Here's the bug: https://github.com/bids-standard/pybids/pull/746 started using `pathlib` in place of `str`-ly paths. But 

https://github.com/bids-standard/pybids/blob/f58bdbec5fd703628741536d7ea9ab47b2c1acab/bids/layout/models.py#L144

was never updated to match the new assumption. Weird that they didn't have a test to catch this?

To be fair, we're ignoring their warning:

> /home/GRAMES.POLYMTL.CA/u108545/sg-252/.venv/lib/python3.8/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.


in

https://github.com/spine-generic/spine-generic/blob/260eafbd2e493382ed0c77517f0cbe18ef27b90f/spinegeneric/cli/params_checker.py#L50-L51

but I tried patching it 

<details>

```diff
--- a/spinegeneric/cli/params_checker.py
+++ b/spinegeneric/cli/params_checker.py
@@ -12,7 +12,7 @@ import logging
 import argparse
 import importlib.resources
 
-from bids import BIDSLayout
+from bids import BIDSLayout, BIDSLayoutIndexer
 
 import spinegeneric as sg
 import spinegeneric.cli
@@ -48,7 +48,7 @@ def main():
 
     # Initialize the layout
     with importlib.resources.path(spinegeneric.config, 'bids_specs.json') as path_sg_layout_config:
-        layout = BIDSLayout(data_path,config_filename=path_sg_layout_config,validate=False)
+        layout = BIDSLayout(data_path,indexer=BIDSLayoutIndexer(config_filename=path_sg_layout_config),validate=False)
 
     Contrast_list = ['T1w', 'T2w', 'T2star', 'MTS']
     query = layout.get(suffix=Contrast_list,extension='nii.gz')
```

</details>

and got the same exception.

I really think the error is on there end. In fact I hunted around `git blame` and was able to match up

* https://github.com/bids-standard/pybids/blame/0.14.0/bids/layout/index.py#L109 (changed in that patch) ->
* https://github.com/bids-standard/pybids/pull/746/ ->
* https://github.com/bids-standard/pybids/blame/0.14.0/bids/layout/index.py#L152 (changed in that patch) ->
* https://github.com/bids-standard/pybids/blame/0.14.0/bids/layout/index.py#L162 (changed in that patch so that now `type(config_path) is Path`) -> 
* https://github.com/bids-standard/pybids/blame/0.14.0/bids/layout/index.py#L164 (which wasn't changed in that patch, and that's okay) ->
* https://github.com/bids-standard/pybids/blame/0.14.0/bids/layout/models.py#L144 (which *also* wasn't changed in that patch, but *should* have been because it's expecting only `str`)

I've submitted a patch: https://github.com/bids-standard/pybids/pull/791

**Comment by kousu** [comment]
Right and the reason this only showed up this week is, of course, that 0.14.0 only came out this week: https://github.com/bids-standard/pybids/releases/tag/0.14.0

**Comment by kousu** [comment]
I've patched this (without review/PR) in 77ad130a37de37c9c7f2dfa3c25cfa59908d3b4e. I want to leave this open until they fix it properly upstream and we can revert that.
